stages:
  - Linux GCC Build

Ubuntu:
  image: ubuntu
  stage: Linux GCC Build
  script:
    - apt update -y && apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype6-dev libxi-dev -y
    - apt install gcc g++ cmake git -y
    - cmake -B build && \
    - cmake --build build

Fedora:
  image: fedora
  stage: Linux GCC Build
  script:
    - yum update -y && yum install freetype-devel libX11-devel libXcursor-devel libXrandr-devel mesa-libGL-devel systemd-devel openal-soft-devel libvorbis-devel libogg-devel flac-devel libXi-devel -y
    - yum install gcc g++ cmake git ninja -y
    - cmake -B build -DCMAKE_MAKE_PROGRAM=ninja -G Ninja && \
    - cmake --build build
